<?php

class GeniusDev_ReCaptcha_Block_Captcha_Google extends Mage_Captcha_Block_Captcha_Zend
{
    protected $_template = 'geniusdev/recaptcha/google.phtml';

    protected function _beforeToHtml()
    {
        $this->setData('site_key', Mage::helper('geniusdev_recaptcha')->getRecaptchaPublicKey());
        $this->setData('theme', Mage::helper('geniusdev_recaptcha')->getRecaptchaTheme());

        return parent::_beforeToHtml(); // TODO: Change the autogenerated stub
    }
}